In [3]:
import pandas as pd
import numpy as np

In [29]:
A  = np.array([
    [3,7],
    [-4,-6],
    [7,8],
    [1,-1],
    [-4,-1],
    [-3,-7]
    
])

In [30]:
A

array([[ 3,  7],
       [-4, -6],
       [ 7,  8],
       [ 1, -1],
       [-4, -1],
       [-3, -7]])

In [31]:
A.shape

(6, 2)

In [32]:
pd.DataFrame(A, columns=['a0','a1'])

a0  a1
0   3   7
1  -4  -6
2   7   8
3   1  -1
4  -4  -1
5  -3  -7

In [33]:
a0 = A[:,0]
a1= A[:,1]

In [34]:
np.cov(a0,a1)

array([[20., 25.],
       [25., 40.]])

In [35]:
np.sum(a0*a1)/5

25.0

In [36]:
A.T @ A/5 #matrix multip --- Same result as for covariance 

array([[20., 25.],
       [25., 40.]])

In [25]:
?@

Object `@` not found.


In [37]:
sigma = A.T @ A/5

In [38]:
np.linalg.eig(sigma) #compute the eigenvalues and right eigenvector of a square array

(array([ 3.07417596, 56.92582404]),
 array([[-0.82806723, -0.56062881],
        [ 0.56062881, -0.82806723]]))

lambda1 = 56,92 highest eigenvalue 
lambda2 = 3...

In [39]:
l, x = np.linalg.eig(sigma)

In [40]:
x

array([[-0.82806723, -0.56062881],
       [ 0.56062881, -0.82806723]])

In [42]:
sigma @ x[:,0]

array([-2.54562438,  1.72347161])

In [43]:
sigma @ x[:,1]

array([-31.91425695, -47.13840945])

In [47]:
print("1st principal component with biggest eigenvalue")
x[:,1]

1st principal component with biggest eigenvalue


array([-0.56062881, -0.82806723])

In [46]:
print("2st principal component with lowest eigenvalue")
x[:,0]

2st principal component with lowest eigenvalue


array([-0.82806723,  0.56062881])

In [49]:
pc1_arr =  A @ x[:,1] #to transform the data 

In [50]:
pc2_arr =  A @ x[:,0]

In [51]:
pc1_arr

array([ -7.47835704,   7.21091862, -10.54893951,   0.26743842,
         3.07058247,   7.47835704])

In [52]:
pc2_arr

array([ 1.44019997, -0.05150393, -1.31144014, -1.38869604,  2.75164011,
       -1.44019997])

In [55]:
df = pd.read_csv('glass.data')

In [57]:
df.describe()

1     1.52101       13.64        4.49        1.10       71.78  \
count  213.000000  213.000000  213.000000  213.000000  213.000000  213.000000   
mean   108.000000    1.518353   13.406761    2.676056    1.446526   72.655023   
std     61.631972    0.003039    0.818371    1.440453    0.499882    0.774052   
min      2.000000    1.511150   10.730000    0.000000    0.290000   69.810000   
25%     55.000000    1.516520   12.900000    2.090000    1.190000   72.280000   
50%    108.000000    1.517680   13.300000    3.480000    1.360000   72.790000   
75%    161.000000    1.519150   13.830000    3.600000    1.630000   73.090000   
max    214.000000    1.533930   17.380000    3.980000    3.500000   75.410000   

             0.06        8.75        0.00      0.00.1         1.1  
count  213.000000  213.000000  213.000000  213.000000  213.000000  
mean     0.499108    8.957934    0.175869    0.057277    2.788732  
std      0.653035    1.426435    0.498245    0.097589    2.105130  
min      0.000000    5.430000    0.000000    0.000000    1.000000  
25%      0.130000    8.240000    0.000000    0.000000    1.000000  
50%      0.560000    8.600000    0.000000    0.000000    2.000000  
75%      0.610000    9.180000    0.000000    0.100000    3.000000  
max      6.210000   16.190000    3.150000    0.510000    7.000000

In [59]:
#not scaled dataset!!
from sklearn.preprocessing import StandardScaler
scaler  = StandardScaler()
df_sclaed = scaler.fit_transform(df)

In [62]:
df_new = pd.DataFrame(df_sclaed)

In [64]:
df_new.describe() #mean 0 and std close to 1

0             1             2             3             4   \
count  2.130000e+02  2.130000e+02  2.130000e+02  2.130000e+02  2.130000e+02   
mean  -6.776009e-17 -5.822416e-15 -1.719021e-15  4.691083e-16 -2.397665e-17   
std    1.002356e+00  1.002356e+00  1.002356e+00  1.002356e+00  1.002356e+00   
min   -1.723938e+00 -2.376110e+00 -3.278544e+00 -1.862164e+00 -2.319047e+00   
25%   -8.619691e-01 -6.046672e-01 -6.206894e-01 -4.078139e-01 -5.143814e-01   
50%    0.000000e+00 -2.220092e-01 -1.307623e-01  5.594332e-01 -1.735002e-01   
75%    8.619691e-01  2.629109e-01  5.183912e-01  6.429366e-01  3.678995e-01   
max    1.723938e+00  5.138502e+00  4.866495e+00  9.073639e-01  4.117593e+00   

                 5             6             7             8             9   \
count  2.130000e+02  2.130000e+02  2.130000e+02  2.130000e+02  2.130000e+02   
mean   1.460021e-14 -5.525054e-17 -3.926176e-16  7.297241e-16 -1.459448e-16   
std    1.002356e+00  1.002356e+00  1.002356e+00  1.002356e+00  1.002356e+00   
min   -3.684153e+00 -7.660897e-01 -2.479079e+00 -3.538076e-01 -5.883011e-01   
25%   -4.856353e-01 -5.665504e-01 -5.044924e-01 -3.538076e-01 -5.883011e-01   
50%    1.747874e-01  9.346424e-02 -2.515204e-01 -3.538076e-01 -5.883011e-01   
75%    5.632713e-01  1.702101e-01  1.560456e-01 -3.538076e-01  4.388147e-01   
max    3.567547e+00  8.765749e+00  5.081972e+00  5.983278e+00  4.649990e+00   

                 10  
count  2.130000e+02  
mean  -1.084161e-15  
std    1.002356e+00  
min   -8.517035e-01  
25%   -8.517035e-01  
50%   -3.755543e-01  
75%    1.005949e-01  
max    2.005192e+00